download_url: https://galaxy.ansible.com/download/pfsensible-core-0.4.2.tar.gz
format_version: 1.0.0
name: core
namespace: pfsensible
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.4.2
version_url: https://galaxy.ansible.com/api/v2/collections/pfsensible/core/versions/0.4.2/
